export const REAPER_STRATEGY_SONNE_V2 = [{
  "inputs": [{
    "internalType": "uint256",
    "name": "exchangeType",
    "type": "uint256",
  }],
  "name": "InvalidExchangeType",
  "type": "error",
}, {
  "anonymous": false,
  "inputs": [{
    "indexed": false,
    "internalType": "address",
    "name": "previousAdmin",
    "type": "address",
  }, {
    "indexed": false,
    "internalType": "address",
    "name": "newAdmin",
    "type": "address",
  }],
  "name": "AdminChanged",
  "type": "event",
}, {
  "anonymous": false,
  "inputs": [{
    "indexed": true,
    "internalType": "address",
    "name": "beacon",
    "type": "address",
  }],
  "name": "BeaconUpgraded",
  "type": "event",
}, {
  "anonymous": false,
  "inputs": [{
    "indexed": false,
    "internalType": "uint8",
    "name": "version",
    "type": "uint8",
  }],
  "name": "Initialized",
  "type": "event",
}, {
  "anonymous": false,
  "inputs": [{
    "indexed": true,
    "internalType": "bytes32",
    "name": "role",
    "type": "bytes32",
  }, {
    "indexed": true,
    "internalType": "bytes32",
    "name": "previousAdminRole",
    "type": "bytes32",
  }, {
    "indexed": true,
    "internalType": "bytes32",
    "name": "newAdminRole",
    "type": "bytes32",
  }],
  "name": "RoleAdminChanged",
  "type": "event",
}, {
  "anonymous": false,
  "inputs": [{
    "indexed": true,
    "internalType": "bytes32",
    "name": "role",
    "type": "bytes32",
  }, {
    "indexed": true,
    "internalType": "address",
    "name": "account",
    "type": "address",
  }, {
    "indexed": true,
    "internalType": "address",
    "name": "sender",
    "type": "address",
  }],
  "name": "RoleGranted",
  "type": "event",
}, {
  "anonymous": false,
  "inputs": [{
    "indexed": true,
    "internalType": "bytes32",
    "name": "role",
    "type": "bytes32",
  }, {
    "indexed": true,
    "internalType": "address",
    "name": "account",
    "type": "address",
  }, {
    "indexed": true,
    "internalType": "address",
    "name": "sender",
    "type": "address",
  }],
  "name": "RoleRevoked",
  "type": "event",
}, {
  "anonymous": false,
  "inputs": [{
    "indexed": true,
    "internalType": "address",
    "name": "implementation",
    "type": "address",
  }],
  "name": "Upgraded",
  "type": "event",
}, {
  "inputs": [],
  "name": "ADMIN",
  "outputs": [{ "internalType": "bytes32", "name": "", "type": "bytes32" }],
  "stateMutability": "view",
  "type": "function",
}, {
  "inputs": [],
  "name": "DEFAULT_ADMIN_ROLE",
  "outputs": [{ "internalType": "bytes32", "name": "", "type": "bytes32" }],
  "stateMutability": "view",
  "type": "function",
}, {
  "inputs": [],
  "name": "FUTURE_NEXT_PROPOSAL_TIME",
  "outputs": [{ "internalType": "uint256", "name": "", "type": "uint256" }],
  "stateMutability": "view",
  "type": "function",
}, {
  "inputs": [],
  "name": "GUARDIAN",
  "outputs": [{ "internalType": "bytes32", "name": "", "type": "bytes32" }],
  "stateMutability": "view",
  "type": "function",
}, {
  "inputs": [],
  "name": "KEEPER",
  "outputs": [{ "internalType": "bytes32", "name": "", "type": "bytes32" }],
  "stateMutability": "view",
  "type": "function",
}, {
  "inputs": [],
  "name": "LTV_SAFETY_ZONE",
  "outputs": [{ "internalType": "uint256", "name": "", "type": "uint256" }],
  "stateMutability": "view",
  "type": "function",
}, {
  "inputs": [],
  "name": "MANTISSA",
  "outputs": [{ "internalType": "uint256", "name": "", "type": "uint256" }],
  "stateMutability": "view",
  "type": "function",
}, {
  "inputs": [],
  "name": "PERCENT_DIVISOR",
  "outputs": [{ "internalType": "uint256", "name": "", "type": "uint256" }],
  "stateMutability": "view",
  "type": "function",
}, {
  "inputs": [],
  "name": "STRATEGIST",
  "outputs": [{ "internalType": "bytes32", "name": "", "type": "bytes32" }],
  "stateMutability": "view",
  "type": "function",
}, {
  "inputs": [],
  "name": "UPGRADE_TIMELOCK",
  "outputs": [{ "internalType": "uint256", "name": "", "type": "uint256" }],
  "stateMutability": "view",
  "type": "function",
}, {
  "inputs": [],
  "name": "allowedLtvDrift",
  "outputs": [{ "internalType": "uint256", "name": "", "type": "uint256" }],
  "stateMutability": "view",
  "type": "function",
}, {
  "inputs": [{
    "internalType": "uint256",
    "name": "_amount",
    "type": "uint256",
  }],
  "name": "authorizedWithdrawUnderlying",
  "outputs": [],
  "stateMutability": "nonpayable",
  "type": "function",
}, {
  "inputs": [],
  "name": "balanceOf",
  "outputs": [{ "internalType": "uint256", "name": "", "type": "uint256" }],
  "stateMutability": "view",
  "type": "function",
}, {
  "inputs": [],
  "name": "balanceOfPool",
  "outputs": [{ "internalType": "uint256", "name": "", "type": "uint256" }],
  "stateMutability": "view",
  "type": "function",
}, {
  "inputs": [],
  "name": "balanceOfWant",
  "outputs": [{ "internalType": "uint256", "name": "", "type": "uint256" }],
  "stateMutability": "view",
  "type": "function",
}, {
  "inputs": [],
  "name": "borrowDepth",
  "outputs": [{ "internalType": "uint256", "name": "", "type": "uint256" }],
  "stateMutability": "view",
  "type": "function",
}, {
  "inputs": [],
  "name": "cWant",
  "outputs": [{
    "internalType": "contract CErc20I",
    "name": "",
    "type": "address",
  }],
  "stateMutability": "view",
  "type": "function",
}, {
  "inputs": [],
  "name": "calculateLTV",
  "outputs": [{ "internalType": "uint256", "name": "ltv", "type": "uint256" }],
  "stateMutability": "view",
  "type": "function",
}, {
  "inputs": [],
  "name": "clearUpgradeCooldown",
  "outputs": [],
  "stateMutability": "nonpayable",
  "type": "function",
}, {
  "inputs": [],
  "name": "comptroller",
  "outputs": [{
    "internalType": "contract IComptroller",
    "name": "",
    "type": "address",
  }],
  "stateMutability": "view",
  "type": "function",
}, {
  "inputs": [],
  "name": "emergencyExit",
  "outputs": [{ "internalType": "bool", "name": "", "type": "bool" }],
  "stateMutability": "view",
  "type": "function",
}, {
  "inputs": [],
  "name": "getCurrentLeverageSnapshot",
  "outputs": [
    { "internalType": "uint256", "name": "realLeverage", "type": "uint256" },
    { "internalType": "uint256", "name": "targetLeverage", "type": "uint256" },
    { "internalType": "uint256", "name": "maxLeverage", "type": "uint256" },
  ],
  "stateMutability": "view",
  "type": "function",
}, {
  "inputs": [{ "internalType": "bytes32", "name": "role", "type": "bytes32" }],
  "name": "getRoleAdmin",
  "outputs": [{ "internalType": "bytes32", "name": "", "type": "bytes32" }],
  "stateMutability": "view",
  "type": "function",
}, {
  "inputs": [{ "internalType": "bytes32", "name": "role", "type": "bytes32" }, {
    "internalType": "uint256",
    "name": "index",
    "type": "uint256",
  }],
  "name": "getRoleMember",
  "outputs": [{ "internalType": "address", "name": "", "type": "address" }],
  "stateMutability": "view",
  "type": "function",
}, {
  "inputs": [{ "internalType": "bytes32", "name": "role", "type": "bytes32" }],
  "name": "getRoleMemberCount",
  "outputs": [{ "internalType": "uint256", "name": "", "type": "uint256" }],
  "stateMutability": "view",
  "type": "function",
}, {
  "inputs": [{ "internalType": "bytes32", "name": "role", "type": "bytes32" }, {
    "internalType": "address",
    "name": "account",
    "type": "address",
  }],
  "name": "grantRole",
  "outputs": [],
  "stateMutability": "nonpayable",
  "type": "function",
}, {
  "inputs": [],
  "name": "harvest",
  "outputs": [{ "internalType": "int256", "name": "roi", "type": "int256" }],
  "stateMutability": "nonpayable",
  "type": "function",
}, {
  "inputs": [{ "internalType": "bytes32", "name": "role", "type": "bytes32" }, {
    "internalType": "address",
    "name": "account",
    "type": "address",
  }],
  "name": "hasRole",
  "outputs": [{ "internalType": "bool", "name": "", "type": "bool" }],
  "stateMutability": "view",
  "type": "function",
}, {
  "inputs": [
    { "internalType": "address", "name": "_vault", "type": "address" },
    { "internalType": "address", "name": "_swapper", "type": "address" },
    {
      "internalType": "address[]",
      "name": "_strategists",
      "type": "address[]",
    },
    {
      "internalType": "address[]",
      "name": "_multisigRoles",
      "type": "address[]",
    },
    { "internalType": "address[]", "name": "_keepers", "type": "address[]" },
    { "internalType": "address", "name": "_cWant", "type": "address" },
    { "internalType": "uint256", "name": "_targetLTV", "type": "uint256" },
  ],
  "name": "initialize",
  "outputs": [],
  "stateMutability": "nonpayable",
  "type": "function",
}, {
  "inputs": [],
  "name": "initiateUpgradeCooldown",
  "outputs": [],
  "stateMutability": "nonpayable",
  "type": "function",
}, {
  "inputs": [],
  "name": "lastHarvestTimestamp",
  "outputs": [{ "internalType": "uint256", "name": "", "type": "uint256" }],
  "stateMutability": "view",
  "type": "function",
}, {
  "inputs": [{
    "internalType": "uint256",
    "name": "amount",
    "type": "uint256",
  }],
  "name": "manualDeleverage",
  "outputs": [],
  "stateMutability": "nonpayable",
  "type": "function",
}, {
  "inputs": [{
    "internalType": "uint256",
    "name": "amount",
    "type": "uint256",
  }],
  "name": "manualReleaseWant",
  "outputs": [],
  "stateMutability": "nonpayable",
  "type": "function",
}, {
  "inputs": [{ "internalType": "uint256", "name": "", "type": "uint256" }],
  "name": "markets",
  "outputs": [{ "internalType": "address", "name": "", "type": "address" }],
  "stateMutability": "view",
  "type": "function",
}, {
  "inputs": [],
  "name": "maxBorrowDepth",
  "outputs": [{ "internalType": "uint256", "name": "", "type": "uint256" }],
  "stateMutability": "view",
  "type": "function",
}, {
  "inputs": [],
  "name": "minWantToLeverage",
  "outputs": [{ "internalType": "uint256", "name": "", "type": "uint256" }],
  "stateMutability": "view",
  "type": "function",
}, {
  "inputs": [],
  "name": "proxiableUUID",
  "outputs": [{ "internalType": "bytes32", "name": "", "type": "bytes32" }],
  "stateMutability": "view",
  "type": "function",
}, {
  "inputs": [],
  "name": "recordedPoolBalance",
  "outputs": [{ "internalType": "uint256", "name": "", "type": "uint256" }],
  "stateMutability": "view",
  "type": "function",
}, {
  "inputs": [{ "internalType": "bytes32", "name": "role", "type": "bytes32" }, {
    "internalType": "address",
    "name": "account",
    "type": "address",
  }],
  "name": "renounceRole",
  "outputs": [],
  "stateMutability": "nonpayable",
  "type": "function",
}, {
  "inputs": [{ "internalType": "bytes32", "name": "role", "type": "bytes32" }, {
    "internalType": "address",
    "name": "account",
    "type": "address",
  }],
  "name": "revokeRole",
  "outputs": [],
  "stateMutability": "nonpayable",
  "type": "function",
}, {
  "inputs": [{
    "internalType": "uint256",
    "name": "_drift",
    "type": "uint256",
  }],
  "name": "setAllowedLtvDrift",
  "outputs": [],
  "stateMutability": "nonpayable",
  "type": "function",
}, {
  "inputs": [{
    "internalType": "uint8",
    "name": "_borrowDepth",
    "type": "uint8",
  }],
  "name": "setBorrowDepth",
  "outputs": [],
  "stateMutability": "nonpayable",
  "type": "function",
}, {
  "inputs": [],
  "name": "setEmergencyExit",
  "outputs": [],
  "stateMutability": "nonpayable",
  "type": "function",
}, {
  "inputs": [{
    "components": [
      {
        "internalType": "enum ReaperBaseStrategyv4.ExchangeType",
        "name": "exType",
        "type": "uint8",
      },
      { "internalType": "address", "name": "start", "type": "address" },
      { "internalType": "address", "name": "end", "type": "address" },
      {
        "components": [{
          "internalType": "enum MinAmountOutKind",
          "name": "kind",
          "type": "uint8",
        }, {
          "internalType": "uint256",
          "name": "absoluteOrBPSValue",
          "type": "uint256",
        }],
        "internalType": "struct MinAmountOutData",
        "name": "minAmountOutData",
        "type": "tuple",
      },
      {
        "internalType": "address",
        "name": "exchangeAddress",
        "type": "address",
      },
    ],
    "internalType": "struct ReaperBaseStrategyv4.SwapStep",
    "name": "_newStep",
    "type": "tuple",
  }, { "internalType": "uint256", "name": "index", "type": "uint256" }],
  "name": "setHarvestSwapStepAtIndex",
  "outputs": [],
  "stateMutability": "nonpayable",
  "type": "function",
}, {
  "inputs": [{
    "components": [
      {
        "internalType": "enum ReaperBaseStrategyv4.ExchangeType",
        "name": "exType",
        "type": "uint8",
      },
      { "internalType": "address", "name": "start", "type": "address" },
      { "internalType": "address", "name": "end", "type": "address" },
      {
        "components": [{
          "internalType": "enum MinAmountOutKind",
          "name": "kind",
          "type": "uint8",
        }, {
          "internalType": "uint256",
          "name": "absoluteOrBPSValue",
          "type": "uint256",
        }],
        "internalType": "struct MinAmountOutData",
        "name": "minAmountOutData",
        "type": "tuple",
      },
      {
        "internalType": "address",
        "name": "exchangeAddress",
        "type": "address",
      },
    ],
    "internalType": "struct ReaperBaseStrategyv4.SwapStep[]",
    "name": "_newSteps",
    "type": "tuple[]",
  }],
  "name": "setHarvestSwapSteps",
  "outputs": [],
  "stateMutability": "nonpayable",
  "type": "function",
}, {
  "inputs": [
    { "internalType": "uint256", "name": "targetLeverage", "type": "uint256" },
    { "internalType": "uint256", "name": "", "type": "uint256" },
    { "internalType": "bool", "name": "triggerHarvest", "type": "bool" },
  ],
  "name": "setLeverage",
  "outputs": [],
  "stateMutability": "nonpayable",
  "type": "function",
}, {
  "inputs": [{
    "internalType": "uint256",
    "name": "_minWantToLeverage",
    "type": "uint256",
  }],
  "name": "setMinWantToLeverage",
  "outputs": [],
  "stateMutability": "nonpayable",
  "type": "function",
}, {
  "inputs": [{ "internalType": "uint256", "name": "_ltv", "type": "uint256" }],
  "name": "setTargetLtv",
  "outputs": [],
  "stateMutability": "nonpayable",
  "type": "function",
}, {
  "inputs": [{
    "internalType": "uint256",
    "name": "_withdrawSlippageTolerance",
    "type": "uint256",
  }],
  "name": "setWithdrawSlippageTolerance",
  "outputs": [],
  "stateMutability": "nonpayable",
  "type": "function",
}, {
  "inputs": [{
    "internalType": "bytes4",
    "name": "interfaceId",
    "type": "bytes4",
  }],
  "name": "supportsInterface",
  "outputs": [{ "internalType": "bool", "name": "", "type": "bool" }],
  "stateMutability": "view",
  "type": "function",
}, {
  "inputs": [{ "internalType": "uint256", "name": "", "type": "uint256" }],
  "name": "swapSteps",
  "outputs": [
    {
      "internalType": "enum ReaperBaseStrategyv4.ExchangeType",
      "name": "exType",
      "type": "uint8",
    },
    { "internalType": "address", "name": "start", "type": "address" },
    { "internalType": "address", "name": "end", "type": "address" },
    {
      "components": [{
        "internalType": "enum MinAmountOutKind",
        "name": "kind",
        "type": "uint8",
      }, {
        "internalType": "uint256",
        "name": "absoluteOrBPSValue",
        "type": "uint256",
      }],
      "internalType": "struct MinAmountOutData",
      "name": "minAmountOutData",
      "type": "tuple",
    },
    { "internalType": "address", "name": "exchangeAddress", "type": "address" },
  ],
  "stateMutability": "view",
  "type": "function",
}, {
  "inputs": [],
  "name": "swapper",
  "outputs": [{
    "internalType": "contract ISwapper",
    "name": "",
    "type": "address",
  }],
  "stateMutability": "view",
  "type": "function",
}, {
  "inputs": [],
  "name": "targetLtv",
  "outputs": [{ "internalType": "uint256", "name": "", "type": "uint256" }],
  "stateMutability": "view",
  "type": "function",
}, {
  "inputs": [],
  "name": "updateBalance",
  "outputs": [],
  "stateMutability": "nonpayable",
  "type": "function",
}, {
  "inputs": [],
  "name": "upgradeProposalTime",
  "outputs": [{ "internalType": "uint256", "name": "", "type": "uint256" }],
  "stateMutability": "view",
  "type": "function",
}, {
  "inputs": [{
    "internalType": "address",
    "name": "newImplementation",
    "type": "address",
  }],
  "name": "upgradeTo",
  "outputs": [],
  "stateMutability": "nonpayable",
  "type": "function",
}, {
  "inputs": [{
    "internalType": "address",
    "name": "newImplementation",
    "type": "address",
  }, { "internalType": "bytes", "name": "data", "type": "bytes" }],
  "name": "upgradeToAndCall",
  "outputs": [],
  "stateMutability": "payable",
  "type": "function",
}, {
  "inputs": [],
  "name": "vault",
  "outputs": [{ "internalType": "address", "name": "", "type": "address" }],
  "stateMutability": "view",
  "type": "function",
}, {
  "inputs": [],
  "name": "want",
  "outputs": [{ "internalType": "address", "name": "", "type": "address" }],
  "stateMutability": "view",
  "type": "function",
}, {
  "inputs": [{
    "internalType": "uint256",
    "name": "_amount",
    "type": "uint256",
  }],
  "name": "withdraw",
  "outputs": [{ "internalType": "uint256", "name": "loss", "type": "uint256" }],
  "stateMutability": "nonpayable",
  "type": "function",
}, {
  "inputs": [],
  "name": "withdrawSlippageTolerance",
  "outputs": [{ "internalType": "uint256", "name": "", "type": "uint256" }],
  "stateMutability": "view",
  "type": "function",
}] as const;
